version: 2.4.{build}

configuration:
  - Release

image:
  - Visual Studio 2022

environment:
  VCPKGDIR: C:\tools\vcpkg\installed\x64-windows
  matrix:
  - QTDIR: C:\Qt\5.15\msvc2019_64
  - QTDIR: C:\Qt\6.5\msvc2019_64

install:
- cmd: |-
    set PATH=%QTDIR%\bin;%VCPKGDIR%\tools\protobuf;%PATH%
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat
    vcpkg install protobuf:x64-windows
    vcpkg install zlib:x64-windows

build_script:
- cmd: |-
    qmake PROTOBUF=%VCPKGDIR% ZLIB=%VCPKGDIR% pbfplugin.pro
    nmake release

artifacts:
- path: pbf.dll

cache:
- C:\tools\vcpkg\installed\
