version: 5.1.{build}

configuration:
  - Release

image:
  - Visual Studio 2022

environment:
  QTDIR: C:\Qt\6.9\msvc2022_64

install:
- cmd: |-
    set PATH=%QTDIR%\bin;%PATH%
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat

build_script:
- cmd: |-
    qmake pbfplugin.pro
    nmake release

artifacts:
- path: release\pbf5.dll
  name: pbf5.dll
