name: Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: QtPBFImagePlugin
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install protobuf compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9862592
      - name: Install android platform, build-tools and ndk
        run:  ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-33" "build-tools;33.0.0" "ndk;23.1.7779620"
      - name: Setup NDK path
        run: echo "ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/23.1.7779620/" >> $GITHUB_ENV
      - name: Install Qt (Desktop)
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.4.0'
      - name: Install Qt (Android)
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.4.0'
          target: 'android'
          arch: 'android_arm64_v8a'
      - name: Install Android Google Protocol Buffers
        run:  git clone https://github.com/tumic0/android_protobuf.git
      - name: Configure build
        run:  qmake pbfplugin.pro PROTOBUF=android_protobuf
      - name: Build project
        run:  make -j2
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libplugins_imageformats_libpbf_arm64-v8a.so
          path: plugins/libplugins_imageformats_libpbf_arm64-v8a.so
