name: Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    name: QtPBFImagePlugin
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config: ['release', 'debug']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qtbase5-dev-tools qt5-qmake
      - name: Configure build
        run: qmake CONFIG+=${{ matrix.config }} pbfplugin.pro
      - name: Build project
        run: make -j4
