name: Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    name: QtPBFImagePlugin
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qtbase5-dev-tools qt5-qmake libprotobuf-dev protobuf-compiler zlib1g-dev
      - name: Configure build
        run: qmake pbfplugin.pro
      - name: Build project
        run: make -j2
