name: OS X

on:
  push:
    branches:
      - master

jobs:
  build:
    name: QtPBFImagePlugin
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install qt6 protobuf
      - name: Configure build
        run: qmake PROTOBUF=/usr/local pbfplugin.pro
      - name: Build project
        run: make -j3
