name: OS X

on:
  push:
    branches:
      - master

jobs:
  build:
    name: QtPBFImagePlugin
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.9.1'
      - name: Configure build
        run: qmake pbfplugin.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64h arm64"
      - name: Build project
        run: make -j3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: libpbf.dylib
          name: libpbf.dylib
