name: OS X

on:
  push:
    branches:
      - master

jobs:
  build:
    name: QtPBFImagePlugin
    runs-on: macos-latest
    steps:
      - name: Set environment variables
        run: echo "PATH=/usr/local/opt/qt@5/bin:$PATH" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install qt5 protobuf
      - name: Configure build
        run: qmake PROTOBUF=/usr/local pbfplugin.pro
      - name: Build project
        run: make -j3
